# ===============================
# Perfil Local
# ===============================
app.environment=local

# ===============================
# Base de datos Local
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_utama_db?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool de conexiones
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
jwt.secret=ut4m4S3cr3tK3yF0rInV3nt0ryM4n4g3m3nt2025!
jwt.expiration=1440

# ===============================
# CORS
# ===============================
cors.allowed-origins=http://localhost:3000,http://localhost:3001

# ===============================
# Security
# ===============================
spring.security.user.name=admin
spring.security.user.password=admin123

# ===============================
# Logging
# ===============================
logging.level.com.utama.my_inventory=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
spring.main.banner-mode=off

# ===============================
# Swagger
# ===============================
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs