# ===============================
# Configuracion Comun
# ===============================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.application.name=${APP_NAME:utama-inventory}
server.port=${PORT:9092}
server.error.include-message=always
server.error.include-binding-errors=always

# Jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Argentina/Buenos_Aires
spring.jackson.default-property-inclusion=non_null

# Cloudinary
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api.key=${CLOUDINARY_API_KEY:}
cloudinary.api.secret=${CLOUDINARY_API_SECRET:}